version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.pm2
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=inventory_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads
      - pm2_logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pm2", "ping", "it-asset-manager"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  uploads:
  pm2_logs:

networks:
  app-network:
    driver: bridge
